// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompanyAttribute("Iulian Margarintescu")]
[assembly: AssemblyCopyrightAttribute("Copyright Iulian Margarintescu © 2015")]
[assembly: AssemblyProductAttribute("HdrHistogram .NET")]
[assembly: AssemblyDescriptionAttribute("A High Dynamic Range (HDR) Histogram")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
